-- FULL DATABASE SETUP SCRIPT
-- Run this in Supabase SQL Editor to set up the complete schema required for the application.

-- 1. Profiles Table (for User Roles)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  role text default 'user', -- 'admin', 'user', 'manager'
  manager_id uuid references public.profiles(id)
);

alter table public.profiles enable row level security;
create policy "Public profiles are viewable by everyone" on public.profiles for select using ( true );

-- 2. Clients Table (Master Pool)
create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  mobile text unique not null,
  is_assigned boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.clients enable row level security;

-- 3. Engagements Table (Active Assignments)
create table if not exists public.engagements (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  status text default 'waiting',
  message text,
  assignment_date date default current_date,
  
  -- Additional fields used in application
  segment text,
  state text,
  fund_amount numeric default 0,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(client_id, user_id)
);

alter table public.engagements enable row level security;

-- 4. Payments Table
create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  amount numeric not null,
  
  -- Additional fields used in application
  account_id text,
  
  date date default current_date,
  status text default 'pending', -- 'verified', 'pending', 'rejected'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.payments enable row level security;

-- 5. Triggers for Updated At
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language 'plpgsql';

drop trigger if exists update_clients_updated_at on public.clients;
create trigger update_clients_updated_at before update on public.clients for each row execute procedure update_updated_at_column();

drop trigger if exists update_engagements_updated_at on public.engagements;
create trigger update_engagements_updated_at before update on public.engagements for each row execute procedure update_updated_at_column();

drop trigger if exists update_payments_updated_at on public.payments;
create trigger update_payments_updated_at before update on public.payments for each row execute procedure update_updated_at_column();

-- 6. RLS Policies

-- Clients: Admin manages all, Users see assigned (or if they have engagement)
create policy "Admin total control clients" on public.clients for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

create policy "Users see clients they engage with" on public.clients for select using (
  exists (select 1 from public.engagements where client_id = public.clients.id and user_id = auth.uid())
);

-- Engagements: Admin manages all, Users manage own
create policy "Admin total control engagements" on public.engagements for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

create policy "Users view/update own engagements" on public.engagements for all using (
  user_id = auth.uid()
);

-- Payments: Admin manages all, Users view/insert own
create policy "Admin manage all payments" on public.payments for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

create policy "Users view/insert own payments" on public.payments for all using (
  user_id = auth.uid()
);

-- 7. Strategies Table (Missing in previous step)
create table if not exists public.strategies (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) not null,
  message text not null,
  scope text not null, -- 'company' or 'team'
  target_team_id uuid references public.profiles(id), -- If scope='team', this is the manager's ID
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.strategies enable row level security;

-- Strategy Policies
create policy "Admins manage all strategies" on public.strategies for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

create policy "Managers manage own team strategies" on public.strategies for all using (
  auth.uid() = author_id
);

create policy "Everyone can view company wide strategies" on public.strategies for select using (
  scope = 'company'
);

create policy "Team members can view their managers strategies" on public.strategies for select using (
  scope = 'team' and target_team_id = (
     select manager_id from public.profiles where id = auth.uid()
  )
);

