-- RUN THIS SCRIPT to add the missing Strategies table functionality
-- It treats the error you saw by only creating what is missing.

-- 1. Create Strategies Table
create table if not exists public.strategies (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) not null,
  message text not null,
  scope text not null, -- 'company' or 'team'
  target_team_id uuid references public.profiles(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
alter table public.strategies enable row level security;

-- 3. Create Policies (Dropping first to avoid "already exists" errors)
drop policy if exists "Admins manage all strategies" on public.strategies;
create policy "Admins manage all strategies" on public.strategies for all using (
  exists (select 1 from public.profiles where id = auth.uid() and role = 'admin')
);

drop policy if exists "Managers manage own team strategies" on public.strategies;
create policy "Managers manage own team strategies" on public.strategies for all using (
  auth.uid() = author_id
);

drop policy if exists "Everyone can view company wide strategies" on public.strategies;
create policy "Everyone can view company wide strategies" on public.strategies for select using (
  scope = 'company'
);

drop policy if exists "Team members can view their managers strategies" on public.strategies;
create policy "Team members can view their managers strategies" on public.strategies for select using (
  scope = 'team' and target_team_id = (
     select manager_id from public.profiles where id = auth.uid()
  )
);
